[project]
authors = [{name = "Andreas Copan", email = "avcopan@gmail.com"}]
description = "Add a short description here"
name = "autochem"
requires-python = ">= 3.11"
version = "2025.2.7"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.sdist]
include = ["autochem", "automol", "autoreact", "molsym"]

