name: test

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Environment
      - name: Download environment files
        run: |
          wget https://raw.githubusercontent.com/Auto-Mech/amech-dev/main/pyproject.toml -P ..
          wget https://raw.githubusercontent.com/Auto-Mech/amech-dev/main/pixi.lock -P ..
          mkdir -p ../src/automech
          touch ../src/automech/__init__.py

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: ../pyproject.toml

      - name: Pip install
        run: |
          pixi run pip install -e . --no-deps

      # Test
      - name: Test
        run: |
          pixi run pytest -n auto -v automol
          pixi run pytest -v autochem
          pixi run pytest -v autoreact
